language: node_js

node_js:
  - lts/*

install:
- pip install --user awscli
- npm install -g yaml-lint

script:
- yamllint src/conferences.yml
- mkdir publish
- npm install
- npm run build
- cp -R index.html thank-you.html dist static publish

deploy:
  on:
    branch: master
  provider: s3
  bucket: www.gotodevops.org
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: us-west-2
  acl: public_read
  cache_control: no-store
  skip_cleanup: true
  local_dir: ./publish

after_deploy:
- aws configure set preview.cloudfront true
- aws cloudfront create-invalidation --distribution-id $WWW_CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
- aws cloudfront create-invalidation --distribution-id $NON_WWW_CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
