version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.0
    working_directory: ~/workspace
    steps:
      - checkout
      - run:
          name: Install dependenies
          command: 'npm install'
      - run:
          name: Generate static site
          command: 'npm run generate'
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - dist/_nuxt
            - dist/fonts
            - dist/favicon.png
            - dist/index.html
            - dist/thank-you.html
  deploy:
    docker:
      - image: circleci/python:3.6.8
    working_directory: ~/workspace
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Install awscli
          command: 'sudo apt-get install awscli'
      - run:
          name: Deploy to S3
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              aws s3 sync ./dist  s3://www.gotodevops.org --delete --acl public-read --exclude "*.js"
              aws s3 sync ./dist  s3://www.gotodevops.org --delete --acl public-read --cache-control max-age=31536000,public --include "*.js"
            elif [ "${CIRCLE_BRANCH}" = "beta" ]; then
              aws s3 sync ./dist  s3://beta.gotodevops.org --delete --acl public-read --exclude "*.js"
              aws s3 sync ./dist  s3://beta.gotodevops.org --delete --acl public-read --cache-control max-age=31536000,public --include "*.js"
            else
              echo "No instruction for branch ${CIRCLE_BRANCH}"
            fi
      - run:
          name: Invalidate CloudFront cache
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              aws configure set preview.cloudfront true
              aws cloudfront create-invalidation --distribution-id $WWW_CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
              aws cloudfront create-invalidation --distribution-id $NON_WWW_CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
            elif [ "${CIRCLE_BRANCH}" = "beta" ]; then
              aws configure set preview.cloudfront true
              aws cloudfront create-invalidation --distribution-id $BETA_CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
            else
              echo "No instruction for branch ${CIRCLE_BRANCH}"
            fi
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only:
                - master
                - beta 
          requires:
            - build
